// 🚀 Frontend Stack Icons
export const Frontend = [
  { icon: "logos:html-5", label: "HTML5" },
  { icon: "logos:css-3", label: "CSS3" },
  { icon: "logos:javascript", label: "JavaScript" },
  { icon: "logos:typescript-icon", label: "TypeScript" },
  { icon: "logos:react", label: "React" },
  // { icon: 'logos:nextjs-icon', label: 'Next.js' },
  { icon: "logos:vitejs", label: "Vite" },
  { icon: "logos:tailwindcss-icon", label: "Tailwind CSS" },
  // { icon: 'logos:sass', label: 'Sass' },
  // { icon: 'logos:bootstrap', label: 'Bootstrap' },
  // { icon: 'logos:vue', label: 'Vue.js' },
  // { icon: 'logos:angular-icon', label: 'Angular' },
  // { icon: 'logos:astro-icon', label: 'Astro' },
  { icon: "logos:redux", label: "Redux" },
  { icon: "logos:jquery", label: "jQuery" },
  // { icon: 'logos:webpack', label: 'Webpack' },
  // { icon: 'logos:babel', label: 'Babel' },
  // { icon: 'logos:storybook-icon', label: 'Storybook' },
];

// 🔧 Backend Stack Icons
export const Backend = [
  { icon: "logos:nodejs-icon", label: "Node.js" },
  { icon: "logos:express", label: "Express.js" },
  // { icon: 'logos:nestjs', label: 'NestJS' },
  // { icon: 'logos:deno', label: 'Deno' },
  { icon: "logos:python", label: "Python" },
  { icon: "logos:django-icon", label: "Django" },
  { icon: "logos:flask", label: "Flask" },
  // { icon: 'logos:rails', label: 'Ruby on Rails' },
  // { icon: 'logos:php', label: 'PHP' },
  // { icon: 'logos:laravel', label: 'Laravel' },
  { icon: "logos:java", label: "Java" },
  // { icon: 'logos:spring-icon', label: 'Spring' },
  // { icon: 'logos:go', label: 'Go' },
  { icon: "logos:rust", label: "Rust" },
  { icon: "logos:fastapi", label: "FastAPI" },
  { icon: "logos:postgresql", label: "PostgreSQL" },
  { icon: "logos:mysql", label: "MySQL" },
  // { icon: 'logos:mongodb-icon', label: 'MongoDB' },
  // { icon: 'logos:redis', label: 'Redis' },
  // { icon: 'logos:graphql', label: 'GraphQL' },
  // { icon: 'logos:prisma', label: 'Prisma' },
  // { icon: 'logos:firebase', label: 'Firebase' },
];

// 🔗 Blockchain Stack Icons
export const Web3 = [
  { icon: "logos:ethereum", label: "Ethereum" },
  { icon: "logos:solana", label: "Solana" },
  // { icon: 'logos:polygon-icon', label: 'Polygon' },
  // { icon: 'logos:bitcoin', label: 'Bitcoin' },
  { icon: "logos:metamask-icon", label: "Metamask" },
  { icon: "logos:web3js", label: "Web3.js" },
  { icon: "logos:ethers", label: "Ethers.js" },
  { icon: "logos:hardhat-icon", label: "Hardhat" },
  { icon: "logos:truffle-icon", label: "Truffle" },
  { icon: "logos:ipfs", label: "IPFS" },
  { icon: "logos:chainlink", label: "Chainlink" },
  { icon: "logos:solidity", label: "Solidity" },
  { icon: "logos:alchemy", label: "Alchemy" },
  { icon: "logos:sui", label: "Sui" },
  // { icon: 'logos:moralis', label: 'Moralis' },
  { icon: "logos:foundry", label: "Foundry" },
  // { icon: 'logos:the-graph', label: 'The Graph' },
];
